# Generated by Django 3.1.7 on 2021-04-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
            ],
            options={
                'db_table': 'attendances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(db_column='endTime')),
            ],
            options={
                'db_table': 'bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Failures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
            ],
            options={
                'db_table': 'failures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttime', models.DateTimeField(db_column='reportTime', unique=True)),
                ('hash', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(db_column='roomName', max_length=20, unique=True)),
                ('xroom', models.PositiveSmallIntegerField(db_column='xRoom')),
                ('yroom', models.PositiveSmallIntegerField(db_column='yRoom')),
                ('archived', models.IntegerField()),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanitizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanitizationtime', models.DateTimeField(db_column='sanitizationTime')),
            ],
            options={
                'db_table': 'sanitizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=127)),
                ('type', models.PositiveIntegerField()),
                ('archived', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workstations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstationname', models.CharField(db_column='workStationName', max_length=20, unique=True)),
                ('xworkstation', models.PositiveSmallIntegerField(db_column='xWorkStation')),
                ('yworkstation', models.PositiveSmallIntegerField(db_column='yWorkStation')),
                ('state', models.PositiveIntegerField()),
                ('archived', models.IntegerField()),
            ],
            options={
                'db_table': 'workStations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Workstation',
        ),
    ]
