# Generated by Django 3.1.7 on 2021-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_auto_20210407_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsFailures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
            ],
            options={
                'db_table': 'roomsFailures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkstationsFailures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(db_column='startTime')),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
            ],
            options={
                'db_table': 'workStationsFailures',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Failures',
        ),
    ]
